### ISSUE TITLE
ValueError: could not broadcast input array from shape (0,512) into shape (512)

### ISSUE THREAD

**Issue by wanghongash** [imatge-upc/retrieval-2016-deepvision#11]
Hello~
when the database is paris and run ranker.py, I have the following error: 
wh@rsliu-X10DAi:~/FR-for-instance/retrieval-2016-deepvision-master$ python ranker.py
Applying PCA
Traceback (most recent call last):
  File "ranker.py", line 165, in <module>
    R.rank()
  File "ranker.py", line 146, in rank
    self.get_query_vectors()
  File "ranker.py", line 71, in get_query_vectors
    self.query_feats[i,:] = self.db_feats[np.where(np.array(self.database_list) == query_file)]
ValueError: could not broadcast input array from shape (0,512) into shape (512)

It is strange because when the database is oxford, it is OK.
I don't know how to fix it. Please help me.
Many thanks.

**Comment by wanghongash** [comment]
I have made sure that the paris database is complete. Extracting features is very well.

**Comment by wanghongash** [comment]
I find that my paris database is merged. After modification, it works.
