### ISSUE TITLE
About ranker.py

### ISSUE THREAD

**Issue by dahwang22** [imatge-upc/retrieval-2016-deepvision#15]
Hi, when I run the .py file, there show the error meessage about that where set params['dataset'] = 'oxford' in my params.py, How can I fix it? Thx :
Traceback (most recent call last):
  File "ranker.py", line 169, in <module>
    R.rank()
  File "ranker.py", line 149, in rank
    self.get_query_vectors()
  File "ranker.py", line 74, in get_query_vectors
    self.query_feats[i,:] = self.db_feats[np.where(np.array(self.database_list) == query_file)]
ValueError: could not broadcast input array from shape (0,512) into shape (512)

**Comment by iWeisskohl** [comment]
hi, @hbfreedow  I meet the same question in ranker.py, have u find any way to solve it ?
